apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  CHROMADB_HOST: "chromadb"
  CHROMADB_PORT: "8000"
  HOST: "0.0.0.0"
  PORT: "8106"
  LANGCHAIN_PROJECT: "rag-docs-integration"
  OLLAMA_BASE_URL: "http://ollama:11434"
