apiVersion: skaffold/v3
kind: Config
metadata:
  name: vectordb

requires:
  - path: ./chroma

profiles:
  - name: local
  - name: pgvector
    patches:
      - op: replace
        path: /requires/0/path
        value: ./pgvector
  - name: ci
